export const featured2023 = [
    {
        Name: 'Make Your Own Project',
        Description: `Make Your Own Open Source Project is an opportunity for individuals or groups to create and contribute to an open source project during the Social Winter of Code Season 3. This program is designed to support and encourage the development of innovative and impactful open source projects that address social and humanitarian issues.

        Participants will have the opportunity to work with experienced mentors and a community of like-minded individuals to develop their project ideas and bring them to fruition. Throughout the program, participants will have access to resources and support to help them develop their skills and knowledge as open source contributors.
        
        The Make Your Own Open Source Project program is open to individuals of all skill levels, from beginners to experienced open source contributors. Whether you are a developer, designer, researcher, or have another area of expertise, there is a place for you in this program.
        
        The Social Winter of Code Season 3 is a great opportunity to make a positive impact on the world through the development of open source projects. We encourage you to apply and become a part of this exciting community of changemakers.`,
        Tag: `feature`,
        TechStack: ["Tech Stack of Your Choice"],
        Owner: 'You will be the owner of the repository'
    },
];

export const projectsData2023 = [
    // {
    //     Name: 'Stunning Scripts',
    //     Repo: 'https://github.com/Subhradeep10/Stunning-Scripts',
    //     Owner: 'Subhradeep Samanta',
    //     github: 'https://github.com/Subhradeep10',
    //     linkedin: '',
    //     Description: `A highly curated collection of scripts spanning in complexity from simple to complex.`,
    //     TechStack: ["Python", "Javascript", "Golang", "Rust"],
    // },
    {
        Name: 'Rezume',
        Repo: 'https://github.com/CatsInTech/Rezume/',
        Owner: 'Praveen Kumar Purushothaman',
        github: 'https://github.com/praveenscience/',
        linkedin: 'https://uk.linkedin.com/in/praveentech/',
        Description: `Rezume is a free online portal for generating resumes without worrying about the styling and formatting. In the web portal, you only need to input the basic information which you want to have on your resume and it will automatically generate a decent resume for you.`,
        TechStack: ["NodeJs", "Google Chrome", "VSCode", "Git"],
    },
    {
        Name: 'User-Auth-Microservice',
        Repo: 'https://github.com/sazamansari/node.js-_microservices',
        Owner: 'Md Shadab Azam Ansari',
        github: 'https://github.com/sazamansari',
        linkedin: '',
        Description: `Express.js is a framework of Node.js for building efficient, scalable Node.js server-side applications. It uses modern JavaScript, is built with JavaScript (preserves compatibility with pure JavaScript) and combines elements of OOP (Object Oriented Programming), FP (Functional Programming), and FRP (Functional Reactive Programming).`,
        TechStack: ["Javascript", "Node.js", "MongoDB", "AUTH"],
    },
    {
        Name: 'Web3.0.World',
        Repo: 'https://github.com/Vikash-8090-Yadav/Web3.0-World',
        Owner: 'Vikash Kumar Yadav ',
        github: 'https://github.com/Vikash-8090-Yadav',
        linkedin: '',
        Description: `One place for the web3 developer to showcase their project . This Repo Web3.World consists of projects (decentralized apps) build on differnet chains.This made for the blockchain developer who want's to learn something while contributing .`,
        TechStack: ["Web3", "Blockchain"],
    },
    {
        Name: 'solidity -Pathshala',
        Repo: 'https://github.com/Vikash-8090-Yadav/Solidity-Pathshala',
        Owner: 'Vikash Kumar Yadav',
        github: 'https://github.com/Vikash-8090-Yadav',
        linkedin: '',
        Description: `One place for the smart contract developer. This repo will have all the smart contract written in the remix ide .It contains all the source code with the screen shot.`,
        TechStack: ["Solidity", "Blockchain"],
    },
    {
        Name: 'Face-X',
        Repo: 'https://github.com/akshitagupta15june/Face-X',
        Owner: 'Akshita Gupta',
        github: 'https://github.com/akshitagupta15june',
        linkedin: '',
        Description: `Demonstration of different algorithms and operations on faces.`,
        TechStack: ["ML", "ANN", "Web", "IoT"],
    },
    {
        Name: 'Css.Effects-Designs',
        Repo: 'https://github.com/WeBeginners-Community/CSS.Effects-Designs',
        Owner: 'Sulagna Dutta Roy',
        github: 'https://github.com/WeBeginners-Community',
        linkedin: '',
        Description: `This respository is specially for newcomers who wants to enhance their knowledge and skills by making small/large projects.Only Css/SAAS/LASS Projects is accepted.`,
        TechStack: ["CSS", "HTML", "Javascript", "Documentation skills"],
    },
    {
        Name: 'Docbook',
        Repo: 'https://github.com/WeBeginners-Community/DocBook',
        Owner: 'Sulagna Dutta Roy',
        github: 'https://github.com/WeBeginners-Community',
        linkedin: '',
        Description: `Documentations of Html to every open source technologies. It's a low-code repository This respository is specially for newcomers who wants to enhance their documentation skills by making small/large projects.        `,
        TechStack: ["CSS", "HTML", "Javascript", "Documentation skills"],
    },
    {
        Name: 'TechOS Bell',
        Repo: 'https://github.com/techos-bell',
        Owner: 'Faeka Ansari',
        github: 'https://github.com/techos-bell',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["HTML", "CSS", "JavaScript", "ReactJS"],
    },
    {
        Name: 'Dino',
        Repo: 'https://github.com/developer-diganta/Dino',
        Owner: 'Diganta Kr Banik',
        github: 'https://github.com/developer-diganta',
        linkedin: '',
        Description: `Dino is a chrome extension to help people with dyslexia and color blindness access web pages with more ease.        `,
        TechStack: ["HTML", "CSS", "JavaScript"],
    },
    {
        Name: 'Deep Learning Simplified',
        Repo: 'https://github.com/World-of-ML/DL-Simplified',
        Owner: 'Abhishek Sharma',
        github: 'https://github.com/World-of-ML',
        linkedin: '',
        Description: `Deep Learning Simplified is an Open-source repository, containing beginner to advance level deep learning projects for the contributors, who are willing to start their journey in Deep Learning. Devfolio URL`,
        TechStack: ["Deep Learning", "Machine Learning", "Tensorflow", "Neural Networks", "Keras"],
    },
    // {
    //     Name: 'Blog application ',
    //     Repo: 'https://github.com/tejeswar68/ERA',
    //     Owner: 'Tejeswara Murthy Palwadi',
    //     github: 'https://github.com/tejeswar68',
    //     linkedin: '',
    //     Description: `Multi Functional Web Application`,
    //     TechStack: ["MERN STACK"],
    // },
    // {
    //     Name: 'Calci',
    //     Repo: 'https://github.com/gh4abhi/Calci.git',
    //     Owner: 'Abhishek Swaroop Shrivastava',
    //     github: 'https://github.com/gh4abhi',
    //     linkedin: '',
    //     Description: `A voice operated calculator built using tkinter in Python.`,
    //     TechStack: ["Python", "tkinter", "Machine Learning", "Python GUI", "NLP"],
    // },
    {
        Name: 'Task Management Application ',
        Repo: 'https://github.com/swarnavopramanik/task-management-application',
        Owner: 'Swarnavo Pramanik',
        github: 'https://github.com/swarnavopramanik',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: [],
    },
    {
        Name: 'Terminal Portfolio',
        Repo: 'https://github.com/techspiritss/terminal-portfolio',
        Owner: 'Sidharth Sethi',
        github: 'https://github.com/techspiritss',
        linkedin: '',
        Description: `Not Everyone is good at making attractive GUI Elements. Some people rock at making CLI. This Project invites all those CLI Lovers to create a CLI Themed Portfolio`,
        TechStack: ["HTML", "CSS", "JavaScript"],
    },
    {
        Name: 'Front-End-Projects',
        Repo: 'https://github.com/TusharKesarwani/Front-End-Projects',
        Owner: 'Tushar Kesarwani',
        github: 'https://github.com/TusharKesarwani',
        linkedin: 'https://www.linkedin.com/in/tushar104',
        Description: `This is a Repository where different types of Front - End Projects are present. If you have any front end project then you can contribute to this open source repository.`,
        TechStack: ["HTML5", "CSS3", "JavaScript"],
    },
    {
        Name: 'Vritaant',
        Repo: 'https://github.com/bhattabhi013/Vritant',
        Owner: 'Abhishek Bhatt',
        github: 'https://github.com/bhattabhi013',
        linkedin: '',
        Description: `Vritaant is a cross-platform application to help the naughty and carefree young ones learn and understand nursery rhymes in a fun and interactive way. It helps to incorporate Augmented Reality based digital learning experience to help children take their first step into formal education        `,
        TechStack: ["Flutter", "AR"],
    },
    // {
    //     Name: 'Web development',
    //     Repo: '',
    //     Owner: 'Shraddha Singh',
    //     github: '',
    //     linkedin: '',
    //     Description: `Coming soon, Stay tuned...`,
    //     TechStack: [],
    // },
    // {
    //     Name: 'Team builder',
    //     Repo: 'https://github.com/MLH-LHD-Build-2022/Team-Builder',
    //     Owner: 'Naresh Chandanbatve',
    //     github: 'https://github.com/MLH-LHD-Build-2022',
    //     linkedin: '',
    //     Description: `Hackathons are a great way to meet new people, but we can choose our right teammates in a rush. No right? We too faced this problem while selecting the teammates. Thus Team Builder was born. A platform where members of hackathons have free will and options to choose from, they could even contact the original idea owner. It is better for both the idea owner and the participant as discussion always result in a better product.        `,
    //     TechStack: ["HTML", "CSS", "JavaScript", "bootstrap", "Firebase", "node.js", "express.js", "cookie-parser"],
    // },
    {
        Name: 'Attack Vectors Suite',
        Repo: 'https://github.com/SANTHOSH17-DOT/attack-vectors-suite',
        Owner: 'Santhosh Murugaiah',
        github: 'https://github.com/SANTHOSH17-DOT',
        linkedin: '',
        Description: `This repository contains a collection of cybersecurity attack vectors. I firmly believe that the best way to learn something is to do it & all my experiments with a particular attack vector have been documented in this repo.        `,
        TechStack: ["Golang", "Javascript", "Solidity", "React"],
    },
    {
        Name: 'Are you bombed',
        Repo: 'https://github.com/SANTHOSH17-DOT/are-you-bombed',
        Owner: 'Santhosh Murugaiah',
        github: 'https://github.com/SANTHOSH17-DOT',
        linkedin: '',
        Description: `A Golang application which can generate flat and nested zip bombs and serve them using Gin HTTP web framework.`,
        TechStack: ["Golang", "Javascript", "Solidity", "React"],
    },
    {
        Name: 'HODL',
        Repo: 'https://github.com/SANTHOSH17-DOT/HODL',
        Owner: 'Santhosh Murugaiah',
        github: 'https://github.com/SANTHOSH17-DOT',
        linkedin: '',
        Description: `Hold On for Dear Life is a time lock wallet to which users can send their crypto and set a HODL time.`,
        TechStack: ["Golang", "Javascript", "Solidity", "React"],
    },
    {
        Name: 'SeamLess UI',
        Repo: 'https://github.com/Clueless-Community/seamless-ui',
        Owner: 'Rajdeep Sengupta',
        github: 'https://github.com/Clueless-Community',
        linkedin: '',
        Description: `This is a Web UI Kit made with simple HTML and Tailwind CSS. You can use them in any of your projects, be it a simple HTML, CSS static website or a React, Vue, Angular or Next.js Complex app.`,
        TechStack: ["HTML", "CSS", "Tailwind CSS", "React"],
    },
    {
        Name: 'Clueless Official Website',
        Repo: 'https://github.com/Clueless-Community/clueless-official-website',
        Owner: 'Debajyoti Saha',
        github: 'https://github.com/Clueless-Community',
        linkedin: '',
        Description: `This is Clueless official website where you can make your developer profile as well as meet new people across the world.`,
        TechStack: ["React", "Firebase", "Typescript", "NextJS", "Tailwind", "Material UI"],
    },
    {
        Name: 'FinTech API',
        Repo: 'https://github.com/Clueless-Community/fintech-api',
        Owner: 'Nikhil Raj',
        github: 'https://github.com/Clueless-Community',
        linkedin: '',
        Description: `An API that helps you to deal with your financial calculations`,
        TechStack: ["Python", "Fast API"],
    },
    {
        Name: 'Rapton - Resume Builder for Developers',
        Repo: 'https://github.com/itsmdasifraza/rapton-react-client',
        Owner: 'Md Asif Raza',
        github: 'https://github.com/itsmdasifraza',
        linkedin: '',
        Description: `Rapton is a Open Source Project that builds resume for developer's which takes input from users like name, email, education, skills, social profiles, work experience, projects, achievements, and then compile the data to generate a resume of selected template.`,
        TechStack: ["React", "Bootstrap", "MaterialUI", "Node", "Express", "MongoDB"],
    },
    {
        Name: 'ARTIST BANK',
        Repo: 'https://github.com/mohit200008/NFT-MARKETPLACE',
        Owner: 'Mohit Lamba',
        github: 'https://github.com/mohit200008',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Reactjs", "Solidity", "Blockchain", "Tailwindcss", "Ganache", "Truffle"],
    },
    // {
    //     Name: 'Translator',
    //     Repo: 'https://github.com/codeNaitik/Translator',
    //     Owner: 'Naitik Pitroda',
    //     github: 'https://github.com/codeNaitik',
    //     linkedin: '',
    //     Description: `This app used to translate text from one language to another one and also speak for you.`,
    //     TechStack: ["Javascript"],
    // },
    {
        Name: 'Codeless Builder',
        Repo: 'https://github.com/orgs/Codeless-Builder/repositories',
        Owner: 'Arya Soni',
        github: 'https://github.com/aryasoni98',
        linkedin: '',
        Description: `We aim to build codeless webapp builder which will be an open-source, free of cost, user-friendly web application for creating attractive websites without writing any piece of code where anyone can quickly draft components with the simple drag and drop UI.`,
        TechStack: ["Core Javascript", "ReactJS", "NextJS", "VueJS", "TypescriptJS", "MongoDB", "NodeJS", "ExpressJS"],
    },
    // {
    //     Name: 'Latest Resume',
    //     Repo: 'https://manojres.vercel.app',
    //     Owner: 'Manoj Mewada',
    //     github: '',
    //     linkedin: '',
    //     Description: `Coming soon, Stay tuned...`,
    //     TechStack: [],
    // },
    {
        Name: 'TerraForge3D',
        Repo: 'https://github.com/Jaysmito101/TerraForge3D',
        Owner: 'Jaysmito Mukherjee',
        github: 'https://github.com/Jaysmito101',
        linkedin: '',
        Description: `TerraForge3D is a powerful cross platform procedural terrain generation and texturing tool.`,
        TechStack: ["C++", "OpenGL", "GLSL", "Vulkan"],
    },
    {
        Name: 'Blog App Backend',
        Repo: 'https://github.com/Anamika1-cpu/Blog-Application',
        Owner: 'Anamika Gour',
        github: 'https://github.com/Anamika1-cpu',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["MongoDB", "NodeJS", "ExpressJS"],
    },
    // {
    //     Name: 'Blog App Frontend',
    //     Repo: 'https://github.com/Anamika1-cpu/BlogApp-Frontend',
    //     Owner: 'Anamika Gour',
    //     github: 'https://github.com/Anamika1-cpu',
    //     linkedin: '',
    //     Description: `Coming soon, Stay tuned...`,
    //     TechStack: ["ReactJS"],
    // },
    {
        Name: 'Algorithms',
        Repo: 'https://github.com/Kumar-laxmi/Algorithms',
        Owner: 'Kumar Laxmikant',
        github: 'https://github.com/Kumar-laxmi',
        linkedin: '',
        Description: `A Repository for algorithms in C, C++, Python and Java`,
        TechStack: ["C", "C++", "Python", "Java"],
    },
    {
        Name: 'Python Voice Assistant',
        Repo: 'https://github.com/subhadip-saha-05/Python-Voice-Assistant',
        Owner: 'Subhadip Saha',
        github: 'https://github.com/subhadip-saha-05',
        linkedin: '',
        Description: `This Voice assistant can greet you, can search items in google, youtube, wikipedia, can open twitter, instagram, facebook, can create todo list.        `,
        TechStack: ["Python"],
    },
    {
        Name: 'DeStore',
        Repo: 'https://github.com/De-store/De-Store',
        Owner: 'Suraj Singla',
        github: 'https://github.com/De-store',
        linkedin: '',
        Description: `DeStore is a completely decentralized platform that will provide a one-stop solution for app deployment. Companies and developers will be able to list their applications on DeStore using the web client and users will be able to download an application using the DeStore mobile application.`,
        TechStack: ["IPFS", "MATIC", "ReactJS", "React-native", "The graph"],
    },
    {
        Name: 'Project-Guidance',
        Repo: 'https://github.com/Kushal997-das/Project-Guidance',
        Owner: 'Kushal Das',
        github: 'https://github.com/Kushal997-das',
        linkedin: '',
        Description: `The Ultimate resources for beginner to advance level projects all at one place`,
        TechStack: [],
    },
    // {
    //     Name: 'Notebook ',
    //     Repo: 'https://github.com/Rajat2024/NoteBook',
    //     Owner: 'Rajat Singh',
    //     github: 'https://github.com/Rajat2024',
    //     linkedin: '',
    //     Description: `Here notebook is created using React as a frontend and NodeJS as a backend. Here you can add , delete and update notes in your Mongoose database. You create a password using express validation , authentication using JWT Token and salting. An easy way to sign up and log in a notebook, context for data passing through the component.`,
    //     TechStack: ["MERN STACK"],
    // },
    // {
    //     Name: 'My Portfolio Web',
    //     Repo: 'https://github.com/Rahul-Bhati/My_Portfolio_Web.git',
    //     Owner: 'Rahul Bhati',
    //     github: 'https://github.com/Rahul-Bhati',
    //     linkedin: '',
    //     Description: `Coming soon, Stay tuned...`,
    //     TechStack: ["HTML" , "CSS" , "JQuery"],
    // },
    {
        Name: 'Driver snoozing system',
        Repo: 'https://github.com/Deep-ghosty/Driver-Snoozing-System',
        Owner: 'Deepanshu bisht',
        github: 'https://github.com/Deep-ghosty',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Python","dlib","fac_utils"],
    },
];
